[workspace]
resolver = "2"
members = [
    "crates/ziti-sys",
    "crates/ziti",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
thiserror = "2"
libc = "0.2"
tracing = "0.1"

ziti-sys = { path = "crates/ziti-sys" }

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3
